package com.carlosjimz87.serializationparcelization.models

enum class CardState(var value: String) {

    CARD_CONFIRM_STAMPING("0"),
    CARD_DISCHARGER("1"),
    CARD_STAMPING("2"),
    CARD_PERSONALIZATION_PENDING("3"),
    CARD_SENT_ACTIVATION_PENDING("4"),
    CARD_ACTIVE("5"),
    CARD_EXPIRED("10"),
    CARD_DOWN("11"),
    CARD_LOW_WITHOUT_RECOVERING("12"),
    CARD_LOST("51"),
    CARD_STOLEN("52"),
    CARD_RECOVERED_LOST("53"),
    CARD_RECOVERED_STOLEN("54"),
    CARD_BACK_ACTIVATE_PENDING("55"),
    CARD_PRECAUTIONARY_BLOCK("56"),
    CARD_ENGAGED("57"),
    CARD_FALSIFIED("58"),
    CARD_TEMPORARY_BLOCKED_BLISTER("60"),
    CARD_NOT_PAYED("62"),
    CARD_RECOVERED_NAILED("63"),
    CARD_MONITORING("72");
}